 #######                                          #####                                            
    #    #####  #  ####   ####  ###### #####     #     # ###### ##### ##### # #    #  ####   ####  
    #    #    # # #    # #    # #      #    #    #       #        #     #   # ##   # #    # #      
    #    #    # # #      #      #####  #    #     #####  #####    #     #   # # #  # #       ####  
    #    #####  # #  ### #  ### #      #####           # #        #     #   # #  # # #  ###      # 
    #    #   #  # #    # #    # #      #   #     #     # #        #     #   # #   ## #    # #    # 
    #    #    # #  ####   ####  ###### #    #     #####  ######   #     #   # #    #  ####   ####  
                                                                                                   
##################################################################################################

### WARNING:  Ensure trailing spaces or tabs on blank lines are removed from this file otherwise errors will pop up.

# ___                                                         
#  |  ._  ._     _|_  _    _. ._   _|    _     _|_ ._     _|_ 
# _|_ | | |_) |_| |_ _>   (_| | | (_|   (_) |_| |_ |_) |_| |_ 
#         |                                        |                                                                                                          
      #################################################

# Full file path to markets.  See markets.yaml for description of markets config file.
# You can override this on the command line using --markets /path/to/alternative.yaml
markets: debug_markets.yaml

# Full Path to Harmonics file. See harmonics.yaml for a description of the harmonics config file
# You can override this on the command line using --markets /path/to/alternative.yaml
harmonics: harmonics.yaml
#harmonics: false 
                                                                                              
# The path where your trend images will be saved.  Override on the command line using --output_path /home/your/preferred/output/folder
output_path: /home/xual/Pictures/patterns

log_level: DEBUG
                                                                                                   
# ___                            __                         
#  |  ._ _|_  _  ._ ._   _. |   (_   _ _|_ _|_ o ._   _   _ 
# _|_ | | |_ (/_ |  | | (_| |   __) (/_ |_  |_ | | | (_| _> 
#                                                     _|                                                                                                 
      ##################################################                                                                                                   

# Prints patterns that have fully formed and hit completion zones.
# Change to formed: false to see all patterns. Override on the command line using --formed true
formed: true

# This limits the search to patterns that completed in the last n candles.  In this case 400. If you only want to see recently occuring actionable patterns I suggest using 10 or less.
# The lower the number the faster the search.  Override on the command line using --limit_to 10
limit_to: 10

# This switch limits the search to bullish, bearish or all trend directions. Override on the command line using --only bullish
only: all

# This is the percentage that harmonic patterns can vary by. or 1.5% variance a shark pattern that would retrace at 1.13 of the XA leg can go 1.5 percent further.
# Increasing this captures more patterns but they may be less reliable. Override on the command line using --pattern_variance 0.05
pattern_variance: 0.03

# Increasing this number means the peak sensitivity is reduced. Ie. there is more space between peaks. This increases performance but may miss patterns.
# Override on the command line using --peak_spacing 12
peak_spacing: 6
                                         
# | \  _. _|_  _.    _  _      ._ _ o ._   _  
# |_/ (_|  |_ (_|   _> (_) |_| | (_ | | | (_| 
#                                          _| 
      ###################################


# There is a facility to override markets.yaml and use a single source and symbol so that a scan of a single stock can be performed.
# --symbol binance:BTCUSDT     or    --symbol yahoo:MSFT
# These do not exist in the config file and are command line only. 


# The interval or time horizon your candles represent. Options are on yahoo are 15m, 1h, 2h, 4h, 1d, 1w, 1m
# Override on the command line using --interval 1d 
interval: 1h

# Biance can return up to 1000 candles for a given interval.  I may wrap this in a new variable in a future release. For now 1000 is the limit
num_ticks: 1000

# Yahoo uses specific period strings ( not candle ticks like binance ).  I may wrap this in a new variable in a future release. For now 1d 20d 400d is advised.
period: 50d

# Time to sleep between api calls.  I recommend no less than .3 of a second.  This stops the api end point from throttling your requests.
sleep_time: 0.3
